[package]
name = "validator_services"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[dependencies]
beacon_node_fallback = { workspace = true }
bls = { workspace = true }
either = { workspace = true }
eth2 = { workspace = true }
futures = { workspace = true }
graffiti_file = { workspace = true }
logging = { workspace = true }
parking_lot = { workspace = true }
safe_arith = { workspace = true }
slot_clock =  { workspace = true }
task_executor = { workspace = true }
tokio =  { workspace = true }
tracing = { workspace = true }
tree_hash =  { workspace = true }
types =  { workspace = true }
validator_metrics = { workspace = true }
validator_store = { workspace = true }
